homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: -33.8591
  longitude: 151.2002
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 3
  # metric for Metric, imperial for Imperial
  unit_system: metric
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: Australia/Melbourne
  # Customization file
  customize: !include customize.yaml

# Show links to resources in log and frontend
#introduction:

# Enables the frontend
frontend:

# Enables configuration UI
config:

http:
  # Secrets are defined in the file secrets.yaml
  api_password: !secret http_password
  # Uncomment this if you are using SSL/TLS, running in Docker container, etc.
  base_url: 192.168.86.26:8123
  ip_ban_enabled: True
  login_attempts_threshold: 2

# Checks for available updates
# Note: This component will send some information about your system to
# the developers to assist with development of Home Assistant.
# For more information, please see:
# https://home-assistant.io/blog/2016/10/25/explaining-the-updater/
updater:
  # Optional, allows Home Assistant developers to focus on popular components.
  # include_used_components: true

# Discover some devices automatically
discovery:

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Enables support for tracking state changes over time
history:

# View all events in a logbook
logbook:

recorder:
  purge_keep_days: 5
  exclude:
    domains:
      - automation
      - weblink
      - updater
    entities:
      - sun.sun # Don't record sun data
      - sensor.last_boot # Comes from 'systemmonitor' sensor platform
      - sensor.date

# Enables a map showing the location of tracked devices
#map:

# Track the sun
sun:

# HOME ALARM PANEL
alarm_control_panel:
  - platform: manual
    name: House Alarm
    code: !secret alarm
    pending_time: 30
    delay_time: 30
    trigger_time: 4
    disarmed:
      trigger_time: 0
    armed_home:
      pending_time: 0
      delay_time: 0

#XIAOMI
xiaomi_aqara:
  gateways:
    - key: !secret xiamo_key
      mac: !secret xiamo_mac
      
      
notify:
  - name: guypb
    platform: pushbullet
    api_key: !secret guy_push_key
  - name: cathypb
    platform: pushbullet
    api_key: !secret cathy_push_key
  - name: jamespb
    platform: pushbullet
    api_key: !secret james_push_key

# Weather prediction
 
weather:
  - platform: bom

# Text to speech
tts:
  - platform: google

group: !include groups.yaml
automation: !include_dir_merge_list automations/
script: !include_dir_merge_named scripts/
sensor: !include_dir_merge_named sensors/
input_boolean: !include_dir_merge_named input_booleans/
binary_sensor: !include_dir_merge_named binary_sensors/
scene: !include scenes.yaml
